# Generated by Django 3.2.4 on 2021-06-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
